### ISSUE TITLE
minor typo error on "naviton_2d.urdf.xacro"

### ISSUE THREAD

**Issue by Jiroh** [tamago117/eg_navigation#21]
it should be;  
<xacro:include filename="$(find eg_navigation)/urdf/base/base.urdf.xacro"/>
  <xacro:include filename="$(find eg_navigation)/urdf/wheel/wheel.urdf.xacro"/>
  <xacro:include filename="$(find eg_navigation)/urdf/sensors/gps/gps.urdf.xacro"/>
  <xacro:include filename="$(find eg_navigation)/urdf/sensors/gim30/gim30.urdf.xacro"/>
  <xacro:include filename="$(find eg_navigation)/urdf/sensors/lrf/lrf.urdf.xacro"/>
  <xacro:include filename="$(find velodyne_description)/urdf/HDL-32E.urdf.xacro"/>
  <xacro:include filename="$(find eg_navigation)/urdf/sensors/imu/imu.urdf.xacro" />

**Comment by tamago117** [comment]
Thanks for finding the typo! I fixed it.

**Comment by Jiroh** [comment]
お世話になります　ドライブモーターが異なるのでgazebo までですが良い感じです　(本命のplatはbild前で苦戦していますが)Sent from Jiro's iPhoneOn Apr 23, 2023, at 17:03, EG ***@***.***> wrote:﻿
Closed #21 as completed.
